SELECT     
(IPMP.FILE_SEQ || IPMP.FILE_TYP || IPMP.FILE_SER || IPMP.FILE_NBR ) AS APPLICATION_NO,     
IPMP.PRIORITY_APPL_ID AS PRIORITY_NO,     
IPMP.COUNTRY_CODE AS PRIORITY_NATIONALITY,     
IPMP.PRIORITY_DATE FROM 

PRODDGIPR.IP_MARK_PRIORITIES IPMP ;