SELECT     
IM.FILE_SEQ||IM.FILE_TYP||IM.FILE_SER|| IM.FILE_NBR AS APPLICATION_NO,    
IM.FILE_SEQ||IM.FILE_TYP||IM.FILE_SER|| IM.FILE_NBR  AS REGISTRATION_NO,     
IM.FILE_SEQ,     
IM.FILE_NBR,     
IM.FILE_TYP,     
IM.FILE_SER,     
IM.REGISTRATION_DUP,     
IM.REGISTRATION_SER,     
IM.REGISTRATION_TYP,     
IM.MAIN_OWNER_PERSON_NBR,     
IM.MAIN_OWNER_ADDR_NBR,     
IM.MARK_CODE,     
IM.APPL_TYP,     
IM.FILING_DATE,     
IM.JOURNAL_CODE AS PUBLICATION_NO,     
IM.PUBLICATION_DATE,     
IM.REGISTRATION_DATE,     
IM.ENTITLEMENT_DATE,     
IM.EXPIRATION_DATE,     
IM.NICE_CLASS_TXT,     
IM.TRANSLATION 
FROM PRODDGIPR.IP_MARK IM WHERE IM.FILE_TYP IN ('V', 'R', 'K', 'D', 'J', 'M'); 

