SELECT
	(IMO.FILE_SEQ || IMO.FILE_TYP || IMO.FILE_SER || IMO.FILE_NBR) AS APPLICATION_NO,
    	IPP.PERSON_NAME OWNER_NAME,
    	IPA.ADDR_STREET OWNER_ADDRESS,
    	IPP.NATIONALITY_COUNTRY_CODE OWNER_NATIONALITY
FROM PRODDGIPR.IP_MARK_OWNERS IMO
LEFT JOIN PRODDGIPR.IP_PERSON IPP ON IMO.PERSON_NBR = IPP.PERSON_NBR
LEFT JOIN PRODDGIPR.IP_PERSON_ADDRESSES IPA ON IMO.PERSON_NBR = IPA.PERSON_NBR AND IMO.ADDR_NBR = IPA.ADDR_NBR ;
