SELECT DISTINCT
	(IP_PROC.FILE_SEQ || IP_PROC.FILE_TYP || IP_PROC.FILE_SER || IP_PROC.FILE_NBR) AS APPLICATION_NO,
	CF_STATUS.STATUS_CODE,
	CF_STATUS.STATUS_NAME
FROM PRODDGIPR.IP_PROC
JOIN PRODDGIPR.CF_STATUS ON IP_PROC.STATUS_CODE = CF_STATUS.STATUS_CODE
WHERE IP_PROC.FILE_TYP IN ('V', 'R', 'K', 'D', 'J')

