SELECT 

--IM.FILE_SEQ||IM.FILE_TYP||IM.FILE_SER|| IM.FILE_NBR AS APPLICATION_NO, 
IM.APPLICATION_ID,

--IM.FILE_SEQ||IM.FILE_TYP||IM.FILE_SER|| IM.FILE_NBR  AS REGISTRATION_NO,  
IM.APPLICATION_NO,

--IM.FILE_SEQ,  
RC.FILE_SEQ_ID,

--IM.FILE_NBR,
RC.EFILING_NO,

--IM.FILE_TYP, 
RC.FILE_TYPE_ID,

--IM.FILE_SER,     
--belum Ketemu,

--IM.MAIN_OWNER_PERSON_NBR,     
OW.TM_OWNER_ID,

--IM.MAIN_OWNER_ADDR_NBR, 
OW.TM_OWNER_ADDRESS,

--IM.MARK_CODE, 
BR.TM_BRAND_ID,

--IM.APPL_TYP,  
RC.FILE_TYPE_ID, 

--IM.REGISTRATION_DATE,  
RE.CREATED_DATE,

--IM.PUBLICATION_DATE,  
RE.REG_START_DATE,

--IM.REGISTRATION_DUP,  data ini di-syncronize dari IPASS
RE.REG_NO,

--IM.EXPIRATION_DATE,  
RE.EXPIRATION_DATE,

IM.CREATED_DATE

FROM TX_TM_GENERAL IM , TX_RECEPTION RC , TX_REGISTRATION RE  , TX_TM_OWNER OW, TX_TM_BRAND BR
WHERE 
RC.RECEPTION_ID = IM.RECEPTION_ID 
AND
RE.APPLICATION_ID = IM.APPLICATION_ID
AND 
OW.APPLICATION_ID = IM.APPLICATION_ID
AND
BR.APPLICATION_ID = IM.APPLICATION_ID

;