SELECT c.*,d.*,g.*  FROM TX_POST_RECEPTION c JOIN TX_POST_RECEPTION_DETAIL d ON c.POST_RECEPTION_ID = d.POST_RECEPTION_ID 
JOIN TX_TM_GENERAL g ON g.APPLICATION_ID = d.APPLICATION_ID 
WHERE 
c.FILE_TYPE_ID = 'PENGAJUAN_KEBERATAN'
AND
g.CREATED_BY = '90d36945-ff3e-4016-9de7-bbe3818c4cfa';

SELECT * FROM TX_TM_GENERAL WHERE APPLICATION_NO='DID2019031641';


SELECT b.EFILING_NO , b.POST_RECEPTION_NO, a.APPLICATION_ID,b.FILE_TYPE_ID, c.POST_OWNER_NAME 
FROM TX_POST_RECEPTION_DETAIL a , TX_POST_RECEPTION b, TX_POST_OWNER c
WHERE 
a.APPLICATION_ID='IPT2019000035' 
AND a.POST_RECEPTION_ID=b.POST_RECEPTION_ID
AND b.POST_RECEPTION_ID=c.POST_RECEPTION_ID 
AND b.FILE_TYPE_ID IN ('PENGAJUAN_KEBERATAN','SURAT_HEARING','SURAT_SANGGAHAN_ATAS_KEBERATAN');



SELECT  b.EFILING_NO , b.POST_RECEPTION_NO, a.APPLICATION_ID,b.FILE_TYPE_ID, c.POST_OWNER_NAME 
FROM TX_POST_RECEPTION_DETAIL a JOIN TX_TM_GENERAL g ON g.APPLICATION_ID = a.APPLICATION_ID
, TX_POST_RECEPTION b, TX_POST_OWNER c
WHERE 1=1 
AND a.POST_RECEPTION_ID=b.POST_RECEPTION_ID
AND b.POST_RECEPTION_ID=c.POST_RECEPTION_ID 
AND b.FILE_TYPE_ID IN ('PENGAJUAN_KEBERATAN' , 'SURAT_HEARING', 'SURAT_SANGGAHAN_ATAS_KEBERATAN')
AND ROWNUM < 6 ;


SELECT COUNT (b.EFILING_NO) 
FROM TX_POST_RECEPTION_DETAIL a JOIN TX_TM_GENERAL g ON g.APPLICATION_ID = a.APPLICATION_ID
, TX_POST_RECEPTION b, TX_POST_OWNER c
WHERE 1=1 
AND a.POST_RECEPTION_ID=b.POST_RECEPTION_ID
AND b.POST_RECEPTION_ID=c.POST_RECEPTION_ID 
AND b.FILE_TYPE_ID IN ('PENGAJUAN_KEBERATAN','SURAT_HEARING','SURAT_SANGGAHAN_ATAS_KEBERATAN');